[env:kb2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_kb2040
framework = arduino
build_flags = -DUSE_TINYUSB
lib_deps =
    adafruit/Adafruit TinyUSB Library
    adafruit/Adafruit NeoPixel
board.upload.use_1200bps_touch=false
